# Generated by Django 5.1.3 on 2024-11-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_alter_specialization_name_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homework_audio/')),
                ('task', models.TextField()),
            ],
        ),
    ]
