# Generated by Django 5.1.3 on 2024-11-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_audiohomework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_audio/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='homework.specialization'),
        ),
    ]
